runtime: custom
env: flex
entrypoint: gunicorn server:app -w 4 -k uvicorn.workers.UvicornWorker
readiness_check:
  app_start_timeout_sec: 1500
resources:
     cpu: 2
     memory_gb: 4.0
     disk_size_gb: 20